### ISSUE TITLE
NPM Release `1.5.1` package contains no files

### ISSUE THREAD

**Issue by benschwarz** [ndench/up-bank-api#23]
The published NPM package contains no files when installed: 

<img width="266" alt="image" src="https://user-images.githubusercontent.com/924/208229889-15386236-b157-48fb-9de5-c0885857b027.png">

This appears to be because the `package.json` includes a `files` directive: 

```
"files": [
    "dist"
  ]
```

Bug present in `1.5.1`, but not `1.5.0`

**Comment by ndench** [comment]
Hi @benschwarz, thanks for reporting, I had no idea! That's very strange, that files directive has been there for quite a while. Maybe I published 1.5.1 incorrectly. I'll have a look and hopefully sort it out soon. Glad 1.5.0 is working for you.

**Comment by ndench** [comment]
Apologies @benschwarz, it's been a crazy start to the year. I tried to fix this a few times and finally realised the issues is due to 2FA tokens on npmjs.com. I've published v1.5.2 with a granular access token and it appears to have worked correctly this time.

**Comment by benschwarz** [comment]
No worries @ndench, thanks for the release & update :-)
